export const defaultCustomization: Types.Customization = {
  FaceTecSessionTimerCustomization: {
    livenessCheckNoInteractionTimeout: 60,
    idScanNoInteractionTimeout: 120,
  },
  FaceTecOCRConfirmationCustomization: {
    backgroundColors: '#ffffff',
    mainHeaderDividerLineColor: '#417FB2',
    mainHeaderDividerLineWidth: -1,
    mainHeaderFont: null,
    mainHeaderTextColor: '#417FB2',
    sectionHeaderFont: null,
    sectionHeaderTextColor: '#333333',
    fieldLabelFont: null,
    fieldLabelTextColor: '#333333',
    fieldValueFont: null,
    fieldValueTextColor: '#333333',
    inputFieldBackgroundColor: undefined,
    inputFieldFont: null,
    inputFieldTextColor: undefined,
    inputFieldBorderColor: '#333333',
    inputFieldBorderWidth: -1,
    inputFieldCornerRadius: -1,
    inputFieldPlaceholderFont: null,
    inputFieldPlaceholderTextColor: undefined,
    showInputFieldBottomBorderOnly: false,
    buttonFont: null,
    buttonTextNormalColor: undefined,
    buttonBackgroundNormalColor: '#417FB2',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#396E99',
    buttonTextDisabledColor: undefined,
    buttonBackgroundDisabledColor: '#66417FB2',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: -1,
  },

  FaceTecIDScanCustomization: {
    showSelectionScreenBrandingImage: false,
    selectionScreenBrandingImage: 0,
    showSelectionScreenDocumentImage: true,
    selectionScreenDocumentImage: 0,
    captureScreenBackgroundColor: undefined,
    captureFrameStrokeColor: '#417FB2',
    captureFrameStrokeWidth: -1,
    captureFrameCornerRadius: -1,
    activeTorchButtonImage: 0,
    inactiveTorchButtonImage: 0,
    selectionScreenBackgroundColors: undefined,
    selectionScreenForegroundColor: '#417FB2',
    reviewScreenBackgroundColors: undefined,
    reviewScreenForegroundColor: undefined,
    reviewScreenTextBackgroundColor: '#417FB2',
    reviewScreenTextBackgroundBorderColor: undefined,
    reviewScreenTextBackgroundBorderWidth: 0,
    reviewScreenTextBackgroundCornerRadius: -1,
    captureScreenForegroundColor: undefined,
    captureScreenTextBackgroundColor: '#417FB2',
    captureScreenTextBackgroundBorderColor: undefined,
    captureScreenTextBackgroundBorderWidth: 0,
    captureScreenTextBackgroundCornerRadius: -1,
    captureScreenFocusMessageTextColor: '#333333',
    captureScreenFocusMessageFont: null,
    headerFont: null,
    subtextFont: null,
    buttonFont: null,
    buttonTextNormalColor: undefined,
    buttonBackgroundNormalColor: '#417FB2',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#396E99',
    buttonTextDisabledColor: undefined,
    buttonBackgroundDisabledColor: '#66417FB2',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: -1,

    customNFCStartingAnimation: 0,
    customNFCScanningAnimation: 0,
    customNFCCardStartingAnimation: 0,
    customNFCCardScanningAnimation: 0,
    customNFCSkipOrErrorAnimation: 0,
    customStaticNFCStartingAnimation: 0,
    customStaticNFCScanningAnimation: 0,
    customStaticNFCSkipOrErrorAnimation: 0,
  },

  FaceTecOverlayCustomization: {
    backgroundColor: undefined,
    brandingImage: undefined,
    showBrandingImage: true,
  },

  FaceTecResultScreenCustomization: {
    animationRelativeScale: 1,
    foregroundColor: '#417FB2',
    backgroundColors: undefined,
    activityIndicatorColor: '#417FB2',
    customActivityIndicatorImage: 0,
    customActivityIndicatorRotationInterval: 1000,
    customActivityIndicatorAnimation: 0,
    showUploadProgressBar: true,
    uploadProgressFillColor: '#417FB2',
    uploadProgressTrackColor: '#66000000',
    resultAnimationBackgroundColor: '#417FB2',
    resultAnimationForegroundColor: undefined,
    resultAnimationSuccessBackgroundImage: 0,
    resultAnimationUnsuccessBackgroundImage: 0,
    customResultAnimationSuccess: 0,
    customResultAnimationUnsuccess: 0,
    customStaticResultAnimationSuccess: 0,
    customStaticResultAnimationUnsuccess: 0,
    messageFont: null,
  },

  FaceTecGuidanceCustomization: {
    backgroundColors: undefined,
    foregroundColor: '#417FB2',
    headerFont: null,
    subtextFont: null,
    readyScreenHeaderFont: null,
    readyScreenHeaderTextColor: undefined,
    readyScreenHeaderAttributedString: '',
    readyScreenSubtextFont: null,
    readyScreenSubtextTextColor: undefined,
    readyScreenSubtextAttributedString: '',
    retryScreenHeaderFont: null,
    retryScreenHeaderTextColor: undefined,
    retryScreenHeaderAttributedString: '',
    retryScreenSubtextFont: null,
    retryScreenSubtextTextColor: undefined,
    retryScreenSubtextAttributedString: '',
    buttonFont: null,
    buttonTextNormalColor: undefined,
    buttonBackgroundNormalColor: '#417FB2',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#396E99',
    buttonTextDisabledColor: undefined,
    buttonBackgroundDisabledColor: '#66417FB2',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: -1,
    readyScreenOvalFillColor: '#00FFFFFF',
    readyScreenTextBackgroundColor: undefined,
    readyScreenTextBackgroundCornerRadius: -1,
    retryScreenImageBorderColor: '#417FB2',
    retryScreenImageBorderWidth: -1,
    retryScreenImageCornerRadius: -1,
    retryScreenOvalStrokeColor: undefined,
    retryScreenIdealImage: 0,
    retryScreenSlideshowImages: undefined,
    retryScreenSlideshowInterval: 1500,
    enableRetryScreenSlideshowShuffle: true,
    cameraPermissionsScreenImage: 0,
  },

  FaceTecFrameCustomization: {
    borderWidth: undefined,
    cornerRadius: undefined,
    borderColor: '#417FB2',
    backgroundColor: undefined,
    elevation: 0,
  },

  FaceTecFeedbackCustomization: {
    cornerRadius: undefined,
    backgroundColors: '#417FB2',
    textColor: undefined,
    textFont: null,
    enablePulsatingText: true,
    elevation: 10,
  },

  FaceTecOvalCustomization: {
    strokeWidth: undefined,
    strokeColor: '#417FB2',
    progressStrokeWidth: undefined,
    progressColor1: '#B3417FB2',
    progressColor2: '#B3417FB2',
    progressRadialOffset: undefined,
  },

  FaceTecCancelButtonCustomization: {
    location: 'topLeft',
  },

  FaceTecExitAnimationStyle: {
    animation: 'circleFade',
  },
};
