// Welcome to the FaceTec Sample App
// This sample demonstrates Initialization, Liveness Check, Enrollment, Authentication, Photo ID Match, Customizing the UX, and Getting Audit Trail Images.
// Please use our technical support form to submit questions and issue reports:  https://dev.facetec.com/

import UIKit
import FaceTecSDK
import LocalAuthentication

class RNOFaceTecViewController: UIViewController, URLSessionDelegate {
    var latestSessionResult: FaceTecSessionResult!
    var latestIDScanResult: FaceTecIDScanResult!
    var utils: RNOUtilities!
    var latestProcessor: Processor!
    var latestExternalDatabaseRefID: String = ""
    var latestServerResult: [String: AnyObject]!
    
    init(bundle: Bundle) {
        super.init(nibName: nil, bundle: bundle)
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Configure initial look and feel of the Sample App
        utils = RNOUtilities(vc: self)
        
        // Initialize FaceTec SDK
        RNOConfig.initializeFaceTecSDKFromAutogeneratedConfig(completion: { initializationSuccessful in
            if(initializationSuccessful) {
                RNOUtilities.updateState(event: ["status": RNOUtilities.getStatus(status: RNOStatus.initialized)])
                
                switch RNOConfig.mode {
                case .authenticate:
                    self.authenticateUser()
                case .enroll:
                    self.enrollUser()
                case .checkLiveness:
                    self.checkLiveness()
                case .matchPhotoID:
                    self.matchPhotoID()
                default:
                    RNOUtilities.updateState(event: ["status": RNOUtilities.getStatus(status: RNOStatus.failed), "message": "Unknown mode was set"])
                }
            }
            else {
                // Displays the FaceTec SDK Status to text field if init failed
                self.utils.displayStatus(statusString: "\(FaceTec.sdk.description(for: FaceTec.sdk.getStatus()))")
                RNOUtilities.updateState(event: ["status": RNOUtilities.getStatus(status: RNOStatus.failed), "message": "Initialization failed, check your configuration properties"])
            }
        })
        
        // Set your FaceTec Device SDK Customizations.
        ThemeHelpers.setAppTheme(theme: utils.currentTheme)
        
        // Set the sound files that are to be used for Vocal Guidance.
        RNOUtilities.setVocalGuidanceSoundFiles()
        utils.setUpVocalGuidancePlayers()
        
        // Set the strings to be used for group names, field names, and placeholder texts for the FaceTec ID Scan User OCR Confirmation Screen.
        RNOUtilities.setOCRLocalization()
        
        // Customize NFC animations
        let currentTheme = RNOConfig.wasSDKConfiguredWithConfigWizard ? "Config Wizard Theme" : "FaceTec Theme"
        utils.handleThemeSelection(theme: currentTheme)
    }
    
    // Initiate a 3D Liveness Check.
    func checkLiveness() {
        // Get a Session Token from the FaceTec SDK, then start the 3D Liveness Check.
        getSessionToken() { sessionToken in
            self.resetLatestResults()
            self.latestProcessor = LivenessCheckProcessor(sessionToken: sessionToken, fromViewController: self)
        }
    }
    
    // Initiate a 3D Liveness Check, then storing the 3D FaceMap in the Database, also known as "Enrollment".  A random externalDatabaseRefID is generated each time to guarantee uniqueness.
    func enrollUser() {
        // Get a Session Token from the FaceTec SDK, then start the Enrollment.
        getSessionToken() { sessionToken in
            self.resetLatestResults()
            self.latestExternalDatabaseRefID = "ios_sample_app_" + UUID().uuidString
            self.latestProcessor = EnrollmentProcessor(sessionToken: sessionToken, fromViewController: self)
        }
    }
    
    // Perform 3D to 3D Authentication against the Enrollment previously performed.
    func authenticateUser() {
        // For demonstration purposes, verify that we have an externalDatabaseRefID to Authenticate against.
        if latestExternalDatabaseRefID.count == 0 {
            RNOUtilities.updateState(event: ["status": RNOUtilities.getStatus(status: RNOStatus.failed), "message": "Please enroll first before trying authentication"])
            return
        }
        
        // Get a Session Token from the FaceTec SDK, then start the 3D to 3D Matching.
        getSessionToken() { sessionToken in
            self.resetLatestResults()
            self.latestProcessor = AuthenticateProcessor(sessionToken: sessionToken, fromViewController: self)
        }
    }
    
    // Perform a 3D Liveness Check, then an ID Scan, then Match the 3D FaceMap to the ID Scan.
    func matchPhotoID() {
        // Get a Session Token from the FaceTec SDK, then start the 3D Liveness Check.  On Success, ID Scanning will start automatically.
        getSessionToken() { sessionToken in
            self.resetLatestResults()
            self.latestExternalDatabaseRefID = "ios_sample_app_" + UUID().uuidString
            self.latestProcessor = PhotoIDMatchProcessor(sessionToken: sessionToken, fromViewController: self)
        }
    }
    
    @IBAction func onPhotoIDScanPressed(_ sender: Any) {
        // Get a Session Token from the FaceTec SDK, then start the Photo ID Scan..
        getSessionToken() { sessionToken in
            self.resetLatestResults()
            self.latestProcessor = PhotoIDScanProcessor(sessionToken: sessionToken, fromViewController: self)
        }
    }
    
    // When the FaceTec SDK is completely done, you receive control back here.
    // Since you have already handled all results in your Processor code, how you proceed here is up to you and how your App works.
    // In general, there was either a Success, or there was some other case where you cancelled out.
    func onComplete() {
        if !self.latestProcessor.isSuccess() {
            // Reset the enrollment identifier.
            self.latestExternalDatabaseRefID = "";
        }
        RNOUtilities.updateState(event: self.latestProcessor.getLastState())
    }
    
    //
    // DEVELOPER NOTE:  This is a convenience function for demonstration purposes only so the Sample App can have access to the latest session results.
    // In your code, you may not even want or need to do this.
    //
    func setLatestSessionResult(sessionResult: FaceTecSessionResult) {
        latestSessionResult = sessionResult
    }
    
    func setLatestIDScanResult(idScanResult: FaceTecIDScanResult) {
        latestIDScanResult = idScanResult
    }
    
    func resetLatestResults() {
        latestSessionResult = nil
        latestIDScanResult = nil
    }
    
    func getLatestExternalDatabaseRefID() -> String {
        return latestExternalDatabaseRefID;
    }
    
    func getSessionToken(sessionTokenCallback: @escaping (String) -> ()) {
        let endpoint = RNOConfig.baseURL + "/session-token"
        let request = NSMutableURLRequest(url: NSURL(string: endpoint)! as URL)
        request.httpMethod = "GET"
        // Required parameters to interact with the FaceTec Managed Testing API.
        request.addValue(RNOConfig.deviceKeyIdentifier, forHTTPHeaderField: "X-Device-Key")
        request.addValue(FaceTec.sdk.createFaceTecAPIUserAgentString(""), forHTTPHeaderField: "User-Agent")
        
        let session = URLSession(configuration: URLSessionConfiguration.default, delegate: self, delegateQueue: OperationQueue.main)
        let task = session.dataTask(with: request as URLRequest, completionHandler: { data, response, error in
            // Ensure the data object is not nil otherwise callback with empty dictionary.
            guard let data = data else {
                print("Exception raised while attempting HTTPS call.")
                self.utils.handleErrorGettingServerSessionToken()
                return
            }
            if let responseJSONObj = try? JSONSerialization.jsonObject(with: data, options: JSONSerialization.ReadingOptions.allowFragments) as? [String: AnyObject] {
                if((responseJSONObj["sessionToken"] as? String) != nil)
                {
                    sessionTokenCallback(responseJSONObj["sessionToken"] as! String)
                    return
                }
                else {
                    print("Exception raised while attempting HTTPS call.")
                    self.utils.handleErrorGettingServerSessionToken()
                }
            }
        })
        task.resume()
    }
}
